// <auto-generated />
using INVENTAR.IO.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INVENTAR.IO.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250908185859_MigrationInventario")]
    partial class MigrationInventario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("INVENTAR.IO.Models.Sector", b =>
                {
                    b.Property<string>("SectorName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SectorName");

                    b.ToTable("Sector");
                });
#pragma warning restore 612, 618
        }
    }
}
